name: Build and Publish Flutter App

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Set up development env variables
        run: echo "${{ secrets.DEVELOPMENT_ENV_FILE }}" > .env

      - name: Build development app
        run: flutter build apk --split-per-abi --no-shrink

      # - name: Publish to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_APP_ID}}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: testers
      #     file: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Send development app to discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Set up production env variables
        run: echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env

      - name: Build production app
        run: flutter build apk --split-per-abi --no-shrink

      - name: Send production app to discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk